#!/usr/bin/env python3
"""Preview removal of the recorded legacy Claude integration; --apply removes it."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import stat
import sys
import tempfile


SHELLS = ('bash', 'zsh', 'fish')
BEGIN = '# >>> claude-usage-dashboard >>>'
END = '# <<< claude-usage-dashboard <<<'
FILE_BEGIN = '# Managed by claude-usage-dashboard; do not edit this file.'
FILE_END = '# End managed claude-usage-dashboard file.'
DIGEST = re.compile(r'[0-9a-f]{64}')


def config_root():
    path = Path(os.environ.get('CLAUDE_CONFIG_DIR') or Path.home() / '.claude').expanduser()
    if not path.is_absolute():
        raise RuntimeError('CLAUDE_CONFIG_DIR must be an absolute path.')
    return path


def record_path():
    return config_root() / 'usage-dashboard/installation.json'


def skill_path():
    return config_root() / 'skills/usage-dashboard/SKILL.md'


def shell_paths(shell):
    config = Path(os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config').expanduser()
    if not config.is_absolute():
        raise RuntimeError('XDG_CONFIG_HOME must be an absolute path.')
    if shell == 'fish':
        return config / 'fish/functions/claude.fish', None
    rc_dir = Path(os.environ.get('ZDOTDIR') or Path.home()).expanduser() if shell == 'zsh' else Path.home()
    if not rc_dir.is_absolute():
        raise RuntimeError('ZDOTDIR must be an absolute path.')
    return config / f'claude-usage-dashboard/{shell}.sh', rc_dir / f'.{shell}rc'


def digest(text):
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def regular(path):
    """Read only files whose ownership and ancestry exclude other-UID writers."""
    directory = path.parent.absolute()
    for ancestor in reversed((directory, *directory.parents)):
        try:
            details = os.lstat(ancestor)
        except FileNotFoundError:
            continue  # Migration never creates or adopts missing directories.
        if stat.S_ISLNK(details.st_mode):
            raise RuntimeError(f'Refusing symlinked installation path: {ancestor}')
        if not stat.S_ISDIR(details.st_mode):
            raise RuntimeError(f'Refusing non-directory installation path: {ancestor}')
        if details.st_uid not in (os.geteuid(), 0):
            raise RuntimeError(f'Refusing foreign-owned installation directory: {ancestor}')
        # Root-owned sticky ancestors protect the user-owned component below
        # them. The target's immediate parent must never be shared writable.
        if details.st_mode & 0o022 and (
                ancestor == directory or details.st_uid != 0 or not details.st_mode & stat.S_ISVTX):
            raise RuntimeError(f'Refusing writable installation directory: {ancestor}')
    try:
        details = os.lstat(path)
    except FileNotFoundError:
        return None
    if stat.S_ISLNK(details.st_mode):
        raise RuntimeError(f'Refusing symlinked installation path: {path}')
    if not stat.S_ISREG(details.st_mode):
        raise RuntimeError(f'Refusing non-regular installation file: {path}')
    if details.st_uid != os.geteuid() or details.st_mode & 0o022:
        raise RuntimeError(f'Refusing foreign-owned or writable installation file: {path}')
    # Preserve CRLF and the exact surrounding startup-file bytes.
    with path.open(encoding='utf-8', newline='') as stream:
        return stream.read()


def split_block(text, path):
    lines = text.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if line.rstrip('\r\n') == BEGIN]
    ends = [i for i, line in enumerate(lines) if line.rstrip('\r\n') == END]
    if not starts and not ends:
        return text, None
    if len(starts) != 1 or len(ends) != 1 or ends[0] <= starts[0] + 1:
        raise RuntimeError(f'Malformed or duplicate managed markers in {path}.')
    start, end = starts[0], ends[0]
    return ''.join(lines[:start] + lines[end + 1:]), ''.join(lines[start:end + 1])


def _unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError('Duplicate installation-record key.')
        result[key] = value
    return result


def _valid_digest(value):
    return isinstance(value, str) and DIGEST.fullmatch(value) is not None


def legacy_content(root):
    return (f'#!/bin/sh\n# Managed by claude-usage-dashboard; checkout: '
            f'{json.dumps(str(root), ensure_ascii=True)}\n'
            f'exec python3 {shlex.quote(str(root / "claude_launcher.py"))} "$@"\n')


def plan_migration(bin_dir=None):
    """Preflight all recorded targets; the recorded checkout need not still exist."""
    path = record_path()
    record_text = regular(path)
    if record_text is None:
        return []  # No record grants no ownership, even for familiar-looking files.
    try:
        record = json.loads(record_text, object_pairs_hook=_unique_object)
    except (ValueError, TypeError) as exc:
        raise RuntimeError('Malformed Claude dashboard installation record.') from exc
    if not isinstance(record, dict) or type(record.get('version')) is not int or record['version'] != 1:
        raise RuntimeError('Unknown Claude dashboard installation record version.')
    installed_root = record.get('root')
    if not isinstance(installed_root, str) or not Path(installed_root).is_absolute():
        raise RuntimeError('Invalid recorded Claude dashboard checkout.')
    shells = record.get('shells')
    if (set(record) != {'version', 'root', 'shells', 'skill', 'skill_digest'}
            or not isinstance(shells, dict) or any(shell not in SHELLS for shell in shells)
            or record.get('skill') != str(skill_path())
            or not _valid_digest(record.get('skill_digest'))):
        raise RuntimeError('Invalid Claude dashboard installation record or target paths.')
    skill = regular(skill_path())
    if skill is None or digest(skill) != record['skill_digest']:
        raise RuntimeError(f'Claude dashboard skill changed or missing: {skill_path()}')
    changes = []
    owner = '# Checkout: ' + json.dumps(installed_root, ensure_ascii=True) + '\n'
    for shell, entry in shells.items():
        managed, rc = shell_paths(shell)
        if (not isinstance(entry, dict)
                or set(entry) != {'managed', 'rc', 'rc_created', 'rc_separator', 'digest', 'block_digest'}
                or entry['managed'] != str(managed)
                or entry['rc'] != (str(rc) if rc else None)
                or type(entry['rc_created']) is not bool
                or type(entry['rc_separator']) is not bool
                or (rc is None and (entry['rc_created'] or entry['rc_separator']))
                or not _valid_digest(entry['digest'])
                or (rc is not None and not _valid_digest(entry['block_digest']))
                or (rc is None and entry['block_digest'] is not None)):
            raise RuntimeError(f'Invalid recorded {shell} hook target or ownership.')
        content = regular(managed)
        if (content is None or digest(content) != entry['digest']
                or not content.startswith(FILE_BEGIN + '\n' + owner)
                or not content.endswith(FILE_END + '\n')):
            raise RuntimeError(f'Claude dashboard shell hook changed or missing: {managed}')
        changes.append((managed, content, None))
        if rc is not None:
            before = regular(rc)
            block = split_block(before, rc)[1] if before is not None else None
            if (block is None or digest(block) != entry['block_digest']
                    or not block.startswith(BEGIN + '\n' + owner)
                    or not block.endswith(END + '\n')):
                raise RuntimeError(f'Claude dashboard shell startup block changed or missing: {rc}')
            position = before.index(block)
            prefix = before[:position]
            if entry['rc_separator']:
                if not prefix.endswith('\n'):
                    raise RuntimeError(f'Claude dashboard startup separator changed: {rc}')
                prefix = prefix[:-1]
            after = prefix + before[position + len(block):]
            if entry['rc_created'] and not after:
                after = None
            changes.append((rc, before, after))
    changes.append((skill_path(), skill, None))
    legacy = Path(bin_dir or Path.home() / '.local/bin').expanduser().absolute() / 'claude-usage'
    wrapper = regular(legacy)
    if wrapper is not None:
        if wrapper != legacy_content(Path(installed_root)):
            raise RuntimeError(f'Refusing foreign or modified legacy wrapper: {legacy}')
        changes.append((legacy, wrapper, None))
    changes.append((path, record_text, None))  # Ownership record is always removed last.
    return changes


def replace_regular(path, old, new, mode=None):
    # This check also protects pathname-based temporary files and rollback:
    # another UID cannot replace any checked ancestor or modify the owned leaf.
    if regular(path) != old:
        raise RuntimeError(f'{path} changed during migration; refusing to overwrite it.')
    if old == new:
        return
    if new is None:
        path.unlink()
        return
    if mode is None:
        mode = stat.S_IMODE(path.stat().st_mode) if old is not None else 0o600
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='', dir=path.parent,
                                         prefix=f'.{path.name}.', delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(new)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        if regular(path) != old:
            raise RuntimeError(f'{path} changed during migration; refusing to overwrite it.')
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def apply_migration(changes):
    # Recheck the complete plan before the first mutation, then each replacement.
    modes = {}
    for path, old, new in changes:
        if regular(path) != old:
            raise RuntimeError(f'{path} changed during migration; refusing to overwrite it.')
        modes[path] = stat.S_IMODE(path.stat().st_mode)
    applied = []
    try:
        for path, old, new in changes:
            if old != new:
                replace_regular(path, old, new, mode=modes[path])
                applied.append((path, old, new))
    except (OSError, RuntimeError, UnicodeError):
        for path, old, new in reversed(applied):
            try:
                replace_regular(path, new, old, mode=modes[path])
            except (OSError, RuntimeError, UnicodeError):
                print(f'Could not roll back {path}; inspect it manually.', file=sys.stderr)
        raise


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--apply', action='store_true', help='explicitly remove proven-owned legacy targets')
    parser.add_argument('--bin-dir', type=Path, default=Path.home() / '.local/bin',
                        help='locate only the obsolete owned claude-usage wrapper')
    args = parser.parse_args(argv)
    try:
        changes = plan_migration(args.bin_dir)
        if not changes:
            print('No recorded legacy integration; no files changed.')
            return 0
        for path, old, new in changes:
            print(f'{"Remove" if new is None else "Edit"}: {path}')
        if args.apply:
            apply_migration(changes)
            print('Removed only proven-owned legacy integration; data, preferences and checkout preserved.')
        else:
            print('Dry run only; no files changed. Use --apply to remove these proven-owned targets.')
    except (OSError, RuntimeError, UnicodeError, ValueError) as exc:
        print(f'Migration failed: {exc}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
