#!/usr/bin/env python3
"""Install Claude's ordinary shell hook and personal usage-dashboard skill."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import pwd
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile


ROOT = Path(__file__).absolute().parent
PRIVATE_TMUX = Path.home() / '.local/share/omp-usage-dashboard/vendor/usr/bin/tmux'
SHELLS = ('bash', 'zsh', 'fish')
BEGIN = '# >>> claude-usage-dashboard >>>'
END = '# <<< claude-usage-dashboard <<<'
FILE_BEGIN = '# Managed by claude-usage-dashboard; do not edit this file.'
FILE_END = '# End managed claude-usage-dashboard file.'


def prerequisites():
    if sys.version_info < (3, 10):
        raise RuntimeError('Python 3.10 or newer is required.')
    try:
        import curses  # noqa: F401
    except ImportError:
        raise RuntimeError('This Python installation lacks curses support.') from None

    claude = shutil.which('claude')
    if not claude:
        raise RuntimeError('Claude CLI must be installed and available on PATH.')

    for candidate in dict.fromkeys(path for path in (shutil.which('tmux'), str(PRIVATE_TMUX)) if path):
        try:
            result = subprocess.run([candidate, '-V'], check=True, capture_output=True,
                                    text=True, timeout=10)
        except (OSError, subprocess.SubprocessError, UnicodeError):
            continue
        version = re.search(r'\btmux\s+(\d+)\.(\d+)', result.stdout)
        if version and tuple(map(int, version.groups())) >= (3, 3):
            return claude, candidate
    raise RuntimeError('tmux 3.3 or newer is required on PATH or at the private tmux fallback.')


def config_root():
    path = Path(os.environ.get('CLAUDE_CONFIG_DIR') or Path.home() / '.claude').expanduser()
    if not path.is_absolute():
        raise RuntimeError('CLAUDE_CONFIG_DIR must be an absolute path.')
    return path


def record_path():
    return config_root() / 'usage-dashboard/installation.json'


def skill_path():
    return config_root() / 'skills/usage-dashboard/SKILL.md'


def selected_shells(value, uninstall=False):
    if value == 'none':
        return ()
    if value == 'all' or (value == 'auto' and uninstall):
        return SHELLS
    if value != 'auto':
        return (value,)
    candidates = [os.environ.get('SHELL', '')]
    try:
        candidates.append(pwd.getpwuid(os.getuid()).pw_shell)
    except KeyError:
        pass
    for candidate in candidates:
        name = Path(candidate).name
        if name in SHELLS:
            return (name,)
    raise RuntimeError('Cannot detect a supported shell; use --shell bash, zsh, fish, all, or none.')


def fish_quote(value):
    return "'" + str(value).replace('\\', '\\\\').replace("'", "\\'") + "'"


def shell_paths(shell):
    config = Path(os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config').expanduser()
    if not config.is_absolute():
        raise RuntimeError('XDG_CONFIG_HOME must be an absolute path.')
    if shell == 'fish':
        return config / 'fish/functions/claude.fish', None
    rc_dir = Path(os.environ.get('ZDOTDIR') or Path.home()).expanduser() if shell == 'zsh' else Path.home()
    if not rc_dir.is_absolute():
        raise RuntimeError('ZDOTDIR must be an absolute path.')
    return config / f'claude-usage-dashboard/{shell}.sh', rc_dir / f'.{shell}rc'


def shell_content(shell, root):
    launcher = root / 'claude_launcher.py'
    if shell == 'fish':
        body = f'''function claude --description 'Claude with account-usage sidebar'
    if status is-interactive
        command python3 {fish_quote(launcher)} $argv
    else
        command claude $argv
    end
end
'''
    else:
        body = f'''case $- in
    *i*)
        if alias claude >/dev/null 2>&1 || typeset -f claude >/dev/null 2>&1; then
            printf '%s\\n' 'claude-usage-dashboard: existing claude alias/function kept; shell hook not loaded.' >&2
        else
            function claude {{
                command python3 {shlex.quote(str(launcher))} "$@"
            }}
        fi
        ;;
esac
'''
    return f'{FILE_BEGIN}\n# Checkout: {json.dumps(str(root), ensure_ascii=True)}\n{body}{FILE_END}\n'


def integration_block(path, root):
    return (f'{BEGIN}\n# Checkout: {json.dumps(str(root), ensure_ascii=True)}\n'
            f'[ ! -f {shlex.quote(str(path))} ] || . {shlex.quote(str(path))}\n{END}\n')


def skill_content(root):
    dashboard = shlex.quote(str(root / 'dashboard.py'))
    updater = shlex.quote(str(root / 'updater.py'))
    return f'''---
description: Control the Claude usage sidebar, including section visibility, and check or explicitly install dashboard updates.
disable-model-invocation: true
---

# Claude usage dashboard

This is a personal Claude Code skill, invoked as `/usage-dashboard`. It applies only to
Claude's Anthropic provider; reject requests for other providers rather than changing them.

With no arguments, explain the available forms and show the current dashboard configuration
with `python3 {dashboard} control --host claude -- view list`. Forms include
`view list|compact|details`, `position left|right`, `providers hide|show anthropic`,
`theme ...`, `window on|off|focus|refresh`, `window interval SECONDS`,
`window hide|show anthropic FILTER`, and
`commands|previous|history-other|history-total hide|show`.

Interpret the user's words as command *data*, not as a shell program. For supported dashboard
settings or display operations, invoke `python3 {dashboard} control --host claude --` followed
by the individually shell-quoted argument tokens that match the requested operation. Never
paste `$ARGUMENTS` or any raw user text into a shell command. Never use `eval`, command
substitution, or a shell expansion to construct arguments. Unsupported commands and provider
names must be rejected. In particular, don't accept `providers add|remove` for non-Anthropic
providers. Run only an operation the user actually requests.

For an update check, run exactly `python3 {updater} --host claude check`.
For an explicitly requested update installation, run exactly
`python3 {updater} --host claude install`. A check is not permission to install.
Do not use OMP's update menu or claim the Claude dashboard is an OMP plugin.

These operations may require the normal Claude Code Bash permission prompt. Do not bypass
permissions or grant broad Bash access. Report denied permission, subprocess errors, and the
actual command result honestly; never claim success without its output.
'''


def digest(text):
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def regular(path):
    """Reject symlinks in the destination or any existing ancestor."""
    for parent in (path, *path.parents):
        if parent.is_symlink():
            raise RuntimeError(f'Refusing symlinked installation path: {parent}')
        if parent != path and parent.exists() and not parent.is_dir():
            raise RuntimeError(f'Refusing non-directory installation path: {parent}')
    if not os.path.lexists(path):
        return None
    if not path.is_file():
        raise RuntimeError(f'Refusing non-regular installation file: {path}')
    return path.read_text(encoding='utf-8')


def split_block(text, path):
    lines = text.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if line.rstrip('\r\n') == BEGIN]
    ends = [i for i, line in enumerate(lines) if line.rstrip('\r\n') == END]
    if not starts and not ends:
        return text, None
    if len(starts) != 1 or len(ends) != 1 or ends[0] <= starts[0] + 1:
        raise RuntimeError(f'Malformed or duplicate managed markers in {path}.')
    start, end = starts[0], ends[0]
    return ''.join(lines[:start] + lines[end + 1:]), ''.join(lines[start:end + 1])


def conflict_paths(shell, managed, rc):
    if shell == 'fish':
        fish_dir = managed.parent.parent
        return [fish_dir / 'config.fish', *sorted((fish_dir / 'conf.d').glob('*.fish'))]
    if shell == 'bash':
        return [rc, *(Path.home() / name for name in ('.bash_aliases', '.bash_profile', '.bash_login', '.profile'))]
    return [rc, *(rc.parent / name for name in ('.zshenv', '.zprofile', '.zlogin'))]


def check_conflicts(shell, managed, rc):
    if shell == 'fish':
        pattern = re.compile(r'(?:^|[;\n])\s*(?:function\s+claude(?:\s|;|$)|alias\s+(?:--\s+)?[\'\"]?claude(?:[\'\"]?\s|=)|abbr\s+[^\n;]*\bclaude\b)')
    else:
        pattern = re.compile(r'(?:^|[;\n])\s*(?:alias\s+(?:--\s+)?[\'\"]?claude\s*=|function\s+claude(?:\s|\(|$)|claude\s*\(\s*\))')
    for path in conflict_paths(shell, managed, rc):
        text = regular(path)
        if text is None:
            continue
        outside, _ = split_block(text, path)
        if pattern.search(outside):
            raise RuntimeError(f'Possible existing claude alias/function/abbreviation in {path}; resolve it before installing.')


def replace_regular(path, old, new):
    if regular(path) != old:
        raise RuntimeError(f'{path} changed during installation; refusing to overwrite it.')
    if old == new:
        return
    if new is None:
        path.unlink()
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = stat.S_IMODE(path.stat().st_mode) if old is not None else 0o600
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=path.parent,
                                         prefix=f'.{path.name}.', delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(new)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        if regular(path) != old:
            raise RuntimeError(f'{path} changed during installation; refusing to overwrite it.')
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def legacy_content(root):
    return (f'#!/bin/sh\n# Managed by claude-usage-dashboard; checkout: '
            f'{json.dumps(str(root), ensure_ascii=True)}\n'
            f'exec python3 {shlex.quote(str(root / "claude_launcher.py"))} "$@"\n')


def owned_legacy(path, root):
    try:
        if not stat.S_ISREG(path.lstat().st_mode):
            return False
        return path.read_text(encoding='utf-8') == legacy_content(root)
    except FileNotFoundError:
        return False


def _shell_entry(shell, root, rc_created=False, rc_separator=False):
    managed, rc = shell_paths(shell)
    content = shell_content(shell, root)
    return {'managed': str(managed), 'rc': str(rc) if rc else None,
            'rc_created': rc_created if rc else False,
            'rc_separator': rc_separator if rc else False,
            'digest': digest(content),
            'block_digest': digest(integration_block(managed, root)) if rc else None}


def _new_record(root, shells, old=None):
    entries = {}
    for shell in shells:
        _, rc = shell_paths(shell)
        if old is not None and shell in old['shells']:
            created = old['shells'][shell]['rc_created']
            separator = old['shells'][shell]['rc_separator']
        else:
            text = regular(rc) if rc is not None else None
            created = rc is not None and text is None
            separator = bool(text) and not text.endswith('\n')
        entries[shell] = _shell_entry(shell, root, created, separator)
    return {'version': 1, 'root': str(root), 'shells': entries,
            'skill': str(skill_path()), 'skill_digest': digest(skill_content(root))}


def _load_record():
    text = regular(record_path())
    if text is None:
        return None
    try:
        record = json.loads(text)
    except (ValueError, TypeError) as exc:
        raise RuntimeError('Malformed Claude dashboard installation record.') from exc
    if not isinstance(record, dict) or record.get('version') != 1:
        raise RuntimeError('Unknown Claude dashboard installation record version.')
    return record


def _validate_record(record, root=None):
    """Check the entire recorded installation before any update or removal."""
    installed_root = record.get('root')
    if not isinstance(installed_root, str) or not Path(installed_root).is_absolute():
        raise RuntimeError('Invalid recorded Claude dashboard checkout.')
    if root is not None and str(Path(root).absolute()) != installed_root:
        raise RuntimeError('Claude dashboard belongs to another checkout.')
    shells = record.get('shells')
    if (set(record) != {'version', 'root', 'shells', 'skill', 'skill_digest'}
            or not isinstance(shells, dict) or any(shell not in SHELLS for shell in shells)
            or record.get('skill') != str(skill_path())
            or not isinstance(record.get('skill_digest'), str)
            or re.fullmatch(r'[0-9a-f]{64}', record['skill_digest']) is None):
        raise RuntimeError('Invalid Claude dashboard installation record or target paths.')
    current_skill = regular(skill_path())
    if current_skill is None or digest(current_skill) != record['skill_digest']:
        raise RuntimeError(f'Claude dashboard skill changed or missing: {skill_path()}')
    for shell, entry in shells.items():
        managed, rc = shell_paths(shell)
        if (not isinstance(entry, dict)
                or set(entry) != {'managed', 'rc', 'rc_created', 'rc_separator', 'digest', 'block_digest'}
                or entry['managed'] != str(managed)
                or entry['rc'] != (str(rc) if rc else None)
                or type(entry['rc_created']) is not bool
                or type(entry['rc_separator']) is not bool
                or (rc is None and (entry['rc_created'] or entry['rc_separator']))
                or not isinstance(entry['digest'], str)
                or re.fullmatch(r'[0-9a-f]{64}', entry['digest']) is None
                or (rc is not None and (not isinstance(entry['block_digest'], str)
                    or re.fullmatch(r'[0-9a-f]{64}', entry['block_digest']) is None))
                or (rc is None and entry['block_digest'] is not None)):
            raise RuntimeError(f'Invalid recorded {shell} hook target or ownership.')
        content = regular(managed)
        owner = '# Checkout: ' + json.dumps(installed_root, ensure_ascii=True) + '\n'
        if (content is None or digest(content) != entry['digest']
                or not content.startswith(FILE_BEGIN + '\n' + owner)
                or not content.endswith(FILE_END + '\n')):
            raise RuntimeError(f'Claude dashboard shell hook changed or missing: {managed}')
        if rc is not None:
            rc_text = regular(rc)
            block = split_block(rc_text, rc)[1] if rc_text is not None else None
            if (block is None or digest(block) != entry['block_digest']
                    or not block.startswith(BEGIN + '\n' + owner)
                    or not block.endswith(END + '\n')):
                raise RuntimeError(f'Claude dashboard shell startup block changed or missing: {rc}')
    return record


def validate_owned_installation(root=ROOT):
    """Return the owned installation record after read-only full ownership checks."""
    record = _load_record()
    if record is None:
        raise RuntimeError('No owned Claude dashboard installation record found.')
    return _validate_record(record, root)


def _plan_shell(shell, root, trusted=False, uninstall=False, remove_empty_rc=False,
                remove_separator=False):
    managed, rc = shell_paths(shell)
    old = regular(managed)
    content = shell_content(shell, root)
    if trusted:
        if old is None:
            raise RuntimeError(f'Claude dashboard shell hook missing: {managed}')
    elif old is not None and old != content:
        raise RuntimeError(f'Refusing to overwrite unowned shell hook: {managed}')
    changes = [(managed, old, None if uninstall else content)]
    if rc is not None:
        before = regular(rc)
        outside, block = split_block(before or '', rc)
        if trusted:
            if block is None:
                raise RuntimeError(f'Claude dashboard shell startup block missing: {rc}')
        elif block is not None and block != integration_block(managed, root):
            raise RuntimeError(f'Refusing to overwrite unowned or modified shell block: {rc}')
        if block is None:
            separator = '\n' if outside and not outside.endswith('\n') else ''
            after = outside + separator + integration_block(managed, root)
        elif uninstall:
            position = before.index(block)
            prefix = before[:position]
            if remove_separator:
                if not prefix.endswith('\n'):
                    raise RuntimeError(f'Claude dashboard startup separator changed: {rc}')
                prefix = prefix[:-1]
            after = prefix + before[position + len(block):]
            if remove_empty_rc and not after:
                after = None
        else:
            after = before.replace(block, integration_block(managed, root), 1)
        changes.append((rc, before, after))
    if not uninstall:
        check_conflicts(shell, managed, rc)
    return changes


def _preflight_assets(root):
    for name in ('claude_launcher.py', 'claude_bridge.py', 'claude_usage_source.py',
                 'dashboard.py', 'updater.py', 'preferences.py', 'host_adapters.py',
                 'session_usage.py', 'usage_source.py', 'package.json'):
        path = root / name
        if not path.is_file() or path.is_symlink():
            raise RuntimeError(f'Incomplete checkout: missing regular {path}.')


def _apply(changes):
    applied = []
    try:
        for path, old, new in changes:
            if old != new:
                replace_regular(path, old, new)
                applied.append((path, old, new))
    except (OSError, RuntimeError, UnicodeError):
        for path, old, new in reversed(applied):
            try:
                replace_regular(path, new, old)
            except (OSError, RuntimeError, UnicodeError):
                print(f'Could not roll back {path}; inspect it manually.', file=sys.stderr)
        raise


def _check_command_collision():
    legacy_command = config_root() / 'commands/usage-dashboard.md'
    if regular(legacy_command) is not None:
        raise RuntimeError(f'Refusing to shadow an existing Claude command: {legacy_command}')


def refresh_owned_installation(root=ROOT):
    """Refresh only exact recorded targets after a managed checkout upgrade."""
    root = Path(root).absolute()
    _preflight_assets(root)
    existing = _load_record()
    if existing is None:
        raise RuntimeError('No owned Claude dashboard installation to refresh.')
    _validate_record(existing, root)
    _check_command_collision()
    shells = tuple(existing['shells'])
    changes = []
    for shell in shells:
        changes.extend(_plan_shell(shell, root, trusted=True))
    skill = skill_path()
    changes.append((skill, regular(skill), skill_content(root)))
    updated = _new_record(root, shells, old=existing)
    changes.append((record_path(), regular(record_path()), json.dumps(updated, indent=2) + '\n'))
    _apply(changes)
    return updated


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--shell', choices=('auto', *SHELLS, 'all', 'none'), default='auto')
    parser.add_argument('--provider', default='anthropic', help='only anthropic is supported')
    parser.add_argument('--bin-dir', type=Path, default=Path.home() / '.local/bin',
                        help='locate only the obsolete owned claude-usage wrapper')
    action = parser.add_mutually_exclusive_group()
    action.add_argument('--uninstall', action='store_true')
    action.add_argument('--refresh', action='store_true')
    args = parser.parse_args(argv)
    root = Path(ROOT).absolute()
    legacy = args.bin_dir.expanduser().absolute() / 'claude-usage'

    try:
        if args.refresh:
            refresh_owned_installation(root)
            print('Refreshed the owned Claude dashboard integration.')
            return 0
        if not args.uninstall and args.provider.lower() not in ('anthropic', 'claude'):
            raise RuntimeError('Claude dashboard only supports the Anthropic provider.')
        record = _load_record()
        if record is not None:
            _validate_record(record, root)
        if args.uninstall:
            shells = tuple(record['shells']) if record is not None else selected_shells(args.shell, True)
        elif record is not None and args.shell == 'auto':
            shells = tuple(record['shells'])
        else:
            shells = selected_shells(args.shell)

        changes = []
        if args.uninstall:
            if record is not None:
                for shell in shells:
                    changes.extend(_plan_shell(shell, root, trusted=True, uninstall=True,
                                               remove_empty_rc=record['shells'][shell]['rc_created'],
                                               remove_separator=record['shells'][shell]['rc_separator']))
                changes.append((skill_path(), regular(skill_path()), None))
                changes.append((record_path(), regular(record_path()), None))
            if owned_legacy(legacy, root):
                changes.append((legacy, regular(legacy), None))
        else:
            _preflight_assets(root)
            _check_command_collision()
            prerequisites()
            for shell in shells:
                changes.extend(_plan_shell(shell, root, trusted=record is not None and shell in record['shells']))
            skill = skill_path()
            current = regular(skill)
            if current is not None and record is None and current != skill_content(root):
                raise RuntimeError(f'Refusing to overwrite unowned or modified Claude skill: {skill}')
            changes.append((skill, current, skill_content(root)))
            updated = _new_record(root, shells, old=record)
            if record is not None and record['shells'] != updated['shells']:
                removed = set(record['shells']) - set(shells)
                for shell in removed:
                    changes.extend(_plan_shell(shell, root, trusted=True, uninstall=True,
                                               remove_empty_rc=record['shells'][shell]['rc_created'],
                                               remove_separator=record['shells'][shell]['rc_separator']))
            changes.append((record_path(), regular(record_path()), json.dumps(updated, indent=2) + '\n'))
            if owned_legacy(legacy, root):
                changes.append((legacy, regular(legacy), None))
        _apply(changes)
    except (OSError, RuntimeError, UnicodeError, ValueError) as exc:
        print(f'{"Uninstall" if args.uninstall else "Installation"} failed: {exc}', file=sys.stderr)
        return 1

    if args.uninstall:
        print('Removed only this checkout\'s owned integration; Claude data and unrelated files were preserved.')
    else:
        print(f'Installed /usage-dashboard skill at {skill_path()} and hooks for {", ".join(shells) or "no shell"}.')
        print('Run ordinary claude in an interactive shell; command claude bypasses the hook.')
        print('Open a new shell to activate bash/zsh; fish autoloads the command. Keep this checkout in place.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
