#!/usr/bin/env python3
"""Install an ordinary omp shell hook and extension without modifying OMP itself."""
import argparse
import json
import os
from pathlib import Path
import pwd
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile

# Preserve the stable node_modules symlink when configuring a native plugin.
ROOT = Path(__file__).absolute().parent
PRIVATE_TMUX = Path.home() / '.local/share/omp-usage-dashboard/vendor/usr/bin/tmux'
SHELLS = ('bash', 'zsh', 'fish')
BEGIN = '# >>> omp-usage-dashboard >>>'
END = '# <<< omp-usage-dashboard <<<'
OWNER = '# Checkout: ' + json.dumps(str(ROOT), ensure_ascii=True)
FILE_BEGIN = '# Managed by omp-usage-dashboard; do not edit this file.'
FILE_END = '# End managed omp-usage-dashboard file.'


def prerequisites():
    if sys.version_info < (3, 10):
        raise RuntimeError('Python 3.10 or newer is required.')
    try:
        import curses
    except ImportError:
        raise RuntimeError('This Python installation lacks curses support.') from None

    omp = shutil.which('omp')
    if not omp:
        raise RuntimeError('OMP must be installed and available on PATH.')
    try:
        subprocess.run([omp, 'usage', '--help'], check=True, capture_output=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        raise RuntimeError('OMP with the usage subcommand is required on PATH.') from None

    candidates = [shutil.which('tmux'), str(PRIVATE_TMUX)]
    for candidate in dict.fromkeys(path for path in candidates if path):
        try:
            result = subprocess.run([candidate, '-V'], check=True, capture_output=True,
                                    text=True, timeout=10)
        except (OSError, subprocess.SubprocessError, UnicodeError):
            continue
        version = re.search(r'\btmux\s+(\d+)\.(\d+)', result.stdout)
        if version and tuple(map(int, version.groups())) >= (3, 3):
            return omp, candidate
    raise RuntimeError('tmux 3.3 or newer is required (PATH or the private fallback).')


def same_link(target, source):
    try:
        return target.is_symlink() and target.resolve() == source
    except (OSError, RuntimeError):
        return False


def selected_shells(value, uninstall=False):
    if value == 'none':
        return ()
    if value == 'all' or (value == 'auto' and uninstall):
        return SHELLS
    if value != 'auto':
        return (value,)
    candidates = [os.environ.get('SHELL', '')]
    try:
        candidates.append(pwd.getpwuid(os.getuid()).pw_shell)
    except KeyError:
        pass
    for candidate in candidates:
        name = Path(candidate).name
        if name in SHELLS:
            return (name,)
    raise RuntimeError('Cannot detect a supported shell; use --shell bash, zsh, fish, all, or none.')


def fish_quote(value):
    return "'" + str(value).replace('\\', '\\\\').replace("'", "\\'") + "'"


def shell_paths(shell):
    config = Path(os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config').expanduser()
    if not config.is_absolute():
        raise RuntimeError('XDG_CONFIG_HOME must be an absolute path.')
    if shell == 'fish':
        return config / 'fish/functions/omp.fish', None
    rc_dir = Path(os.environ.get('ZDOTDIR') or Path.home()).expanduser() if shell == 'zsh' else Path.home()
    return config / f'omp-usage-dashboard/{shell}.sh', rc_dir / f'.{shell}rc'


def shell_content(shell, native=False):
    quote = fish_quote if shell == 'fish' else shlex.quote
    launcher = quote(str(ROOT / 'launcher.py'))
    if native:
        launcher += ' --native'
    if shell == 'fish':
        body = f'''function omp --description 'OMP with account-usage sidebar'
    if status is-interactive
        command python3 {launcher} -- $argv
    else
        command omp $argv
    end
end
'''
    else:
        body = f'''case $- in
    *i*)
        if alias omp >/dev/null 2>&1 || typeset -f omp >/dev/null 2>&1; then
            printf '%s\\n' 'omp-usage-dashboard: existing omp alias/function kept; shell hook not loaded.' >&2
        else
            function omp {{
                command python3 {launcher} -- "$@"
            }}
        fi
        ;;
esac
'''
    return f'{FILE_BEGIN}\n{OWNER}\n{body}{FILE_END}\n'


def read_regular(path):
    if not os.path.lexists(path):
        return None
    if path.is_symlink() or not path.is_file():
        raise RuntimeError(f'Refusing to modify non-regular file or symlink: {path}')
    return path.read_text(encoding='utf-8')


def owned_file(text):
    return (text is not None and text.startswith(f'{FILE_BEGIN}\n{OWNER}\n')
            and text.endswith(f'{FILE_END}\n'))


def split_block(text, path):
    """Return text outside a single well-formed managed block, plus its owner."""
    lines = text.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if line.rstrip('\r\n') == BEGIN]
    ends = [i for i, line in enumerate(lines) if line.rstrip('\r\n') == END]
    if not starts and not ends:
        return text, None
    if len(starts) != 1 or len(ends) != 1 or ends[0] <= starts[0] + 1:
        raise RuntimeError(f'Malformed or duplicate managed markers in {path}; inspect them manually.')
    start, end = starts[0], ends[0]
    owner = lines[start + 1].rstrip('\r\n')
    if not owner.startswith('# Checkout: '):
        raise RuntimeError(f'Missing checkout owner inside managed markers in {path}.')
    return ''.join(lines[:start] + lines[end + 1:]), owner


def integration_block(path):
    return f'{BEGIN}\n{OWNER}\n[ ! -f {shlex.quote(str(path))} ] || . {shlex.quote(str(path))}\n{END}\n'


def find_conflicts(shell, rc, managed):
    """Inspect common startup files without executing arbitrary user shell code."""
    if shell == 'fish':
        fish_dir = managed.parent.parent
        paths = [fish_dir / 'config.fish', *sorted((fish_dir / 'conf.d').glob('*.fish'))]
        pattern = re.compile(r'(?:^|[;\n])\s*(?:function\s+omp(?:\s|;|$)|alias\s+(?:--\s+)?[\'\"]?omp(?:[\'\"]?\s|=)|abbr\s+[^\n;]*\bomp\b)')
    else:
        paths = [rc]
        if shell == 'bash':
            paths += [Path.home() / name for name in ('.bash_aliases', '.bash_profile', '.bash_login', '.profile')]
        else:
            paths += [rc.parent / name for name in ('.zshenv', '.zprofile', '.zlogin')]
        pattern = re.compile(r'(?:^|[;\n])\s*(?:alias\s+(?:--\s+)?[\'\"]?omp\s*=|function\s+omp(?:\s|\(|$)|omp\s*\(\s*\))')
    for path in paths:
        if path == managed or not path.is_file():
            continue
        text = path.read_text(encoding='utf-8')
        if shell == 'fish' and path == fish_dir / 'conf.d/omp-usage-dashboard.fish' and owned_file(text):
            continue
        text, owner = split_block(text, path)
        if owner is not None and owner != OWNER:
            raise RuntimeError(f'Another checkout already owns the shell hook in {path}.')
        if pattern.search(text):
            raise RuntimeError(f'Possible existing omp alias/function/abbreviation in {path}; resolve it before installing.')


def plan_shell(shell, uninstall, native=False):
    managed, rc = shell_paths(shell)
    changes = []
    if shell == 'fish':
        legacy = managed.parent.parent / 'conf.d/omp-usage-dashboard.fish'
        if legacy.is_file() and not legacy.is_symlink():
            previous = legacy.read_text(encoding='utf-8')
            if owned_file(previous):
                changes.append((legacy, previous, None))
    if uninstall:
        # An unrelated destination is not ours to remove, including symlinks.
        if managed.is_file() and not managed.is_symlink():
            old = managed.read_text(encoding='utf-8')
            if owned_file(old):
                changes.append((managed, old, None))
        if rc is not None and rc.is_file() and not rc.is_symlink():
            old = rc.read_text(encoding='utf-8')
            outside, owner = split_block(old, rc)
            if owner == OWNER:
                changes.append((rc, old, outside))
        return changes, managed

    old = read_regular(managed)
    if old is not None and not owned_file(old):
        raise RuntimeError(f'Refusing to overwrite unowned shell hook: {managed}')
    changes.append((managed, old, shell_content(shell, native)))
    if rc is not None:
        previous = read_regular(rc)
        outside, owner = split_block(previous or '', rc)
        if owner is not None and owner != OWNER:
            raise RuntimeError(f'Another checkout already owns the shell hook in {rc}.')
        separator = '\n' if outside and not outside.endswith('\n') else ''
        changes.append((rc, previous, outside + separator + integration_block(managed)))
    find_conflicts(shell, rc, managed)
    return changes, managed


def replace_regular(path, old, new):
    """Recheck ownership assumptions, then atomically replace a regular file."""
    if read_regular(path) != old:
        raise RuntimeError(f'{path} changed during installation; refusing to overwrite it.')
    if old == new:
        return
    if new is None:
        path.unlink()
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = stat.S_IMODE(path.stat().st_mode) if old is not None else 0o600
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=path.parent,
                                         prefix=f'.{path.name}.', delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(new)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        if read_regular(path) != old:
            raise RuntimeError(f'{path} changed during installation; refusing to overwrite it.')
        temporary.replace(path)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--agent-dir', type=Path,
                        default=Path(os.environ.get('PI_CODING_AGENT_DIR') or Path.home() / '.omp/agent'),
                        help='OMP agent directory; for a named profile use ~/.omp/profiles/NAME/agent')
    parser.add_argument('--bin-dir', type=Path, default=Path.home() / '.local/bin',
                        help='only locate/remove the old owned omp-dashboard symlink; no executable is installed')
    parser.add_argument('--shell', choices=('auto', *SHELLS, 'all', 'none'), default='auto',
                        help='shell hook to install (auto: SHELL, then login shell); uninstall auto checks all shells')
    parser.add_argument('--uninstall', action='store_true',
                        help='remove only this checkout\'s managed hooks and extension link; preserve preferences')
    parser.add_argument('--native', action='store_true',
                        help='configure shell hooks only; invoke through the native node_modules package path')
    args = parser.parse_args()
    agent_dir = args.agent_dir.expanduser().absolute()
    legacy = args.bin_dir.expanduser().absolute() / 'omp-dashboard'
    extension = agent_dir / 'extensions/usage-dashboard.js'
    source = ROOT / 'extension.js'
    applied = []
    extension_created = False
    try:
        if args.native and (ROOT.parent.name != 'node_modules' or ROOT.name != 'oh-my-pi-usage-dashboard'):
            raise RuntimeError('Native setup must run through plugins/node_modules/oh-my-pi-usage-dashboard/install.py, not its versioned cache directory.')
        shells = selected_shells(args.shell, args.uninstall)
        plans = [plan_shell(shell, args.uninstall, args.native) for shell in shells]
        if not args.uninstall:
            for name in ('extension.js', 'dashboard.py', 'usage_source.py', 'session_usage.py', 'launcher.py', 'preferences.py', 'updater.py', 'package.json'):
                if not (ROOT / name).is_file():
                    raise RuntimeError(f'Incomplete checkout: missing {name}.')
            if os.path.lexists(extension) and not same_link(extension, source):
                raise RuntimeError(f'Refusing to overwrite {extension}; move it yourself before installing.')
            omp, tmux = prerequisites()
            if not args.native:
                extension.parent.mkdir(parents=True, exist_ok=True)
                if not same_link(extension, source):
                    extension.symlink_to(source)
                    extension_created = True
        for changes, _ in plans:
            for path, old, new in changes:
                replace_regular(path, old, new)
                applied.append((path, old, new))
        if args.uninstall and not args.native and same_link(extension, source):
            extension.unlink()
        if same_link(legacy, ROOT / 'dashboard.py'):
            legacy.unlink()
            print(f'Removed obsolete owned link: {legacy}')
    except (OSError, RuntimeError, UnicodeError) as exc:
        for path, old, new in reversed(applied):
            try:
                replace_regular(path, new, old)
            except (OSError, RuntimeError, UnicodeError):
                print(f'Could not roll back {path}; inspect it manually.', file=sys.stderr)
        if extension_created and same_link(extension, source):
            extension.unlink()
        print(f'{"Uninstall" if args.uninstall else "Installation"} failed: {exc}', file=sys.stderr)
        return 1
    if args.uninstall:
        print('Removed this checkout\'s managed integration where found; unrelated files were kept.')
        print('OMP binary, credentials, preferences, checkout, and private tmux were preserved.')
        print('Open a new shell to discard the loaded omp function; restart OMP to unload the extension.')
        return 0
    if args.native:
        print('OMP manages extension discovery and updates; shell hooks follow its stable package path.')
    else:
        print(f'{extension} -> {source}')
    print(f'Prerequisites: OMP {omp}; tmux {tmux}')
    print('Installed. Run ordinary omp in fish; open a new shell for bash/zsh. Keep this checkout in place.')
    for shell, (_, managed) in zip(shells, plans):
        quote = fish_quote if shell == 'fish' else shlex.quote
        print(f'Activate in the current {shell} shell: source {quote(str(managed))}')
    if not shells:
        print('No shell hook requested. The extension can attach when OMP starts inside tmux.')
    else:
        print('Fish autoload also works in existing shells; non-TTY calls bypass the dashboard. command omp bypasses the hook.')
        print('Conflict checks inspect common startup files, not dynamically sourced code.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
